<a href="https://colab.research.google.com/github/sivahere4cloud/Hugging-face/blob/main/Higging_face_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Practical - 1 Load real tokenizer

In [ ]:
pip install -U transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 36.2 MB/s eta 0:00:00
  Attempting uninstall: transformers
    Found existing installation: transformers 5.13.1
    Uninstalling transformers-5.13.1:
      Successfully uninstalled transformers-5.13.1


In [ ]:
from transformers import AutoTokenizer
MODEL_ID = "distilbert/distilgpt2"
tokenizer =  AutoTokenizer.from_pretrained(MODEL_ID)
print(tokenizer)

config.json:   0%|          | 0.00/762 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

GPT2Tokenizer(name_or_path='distilbert/distilgpt2', vocab_size=50257, model_max_length=1024, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}, added_tokens_decoder={
	50256: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
})


Practical 2 -Tokenize Text

In [ ]:
text = "Siva is learning Hugging Face"
tokens = tokenizer.tokenize(text)
print(tokens)

['S', 'iva', 'Ġis', 'Ġlearning', 'ĠHug', 'ging', 'ĠFace']


practical - 3  Convert tokens into token ids

In [ ]:
token_ids = tokenizer.convert_tokens_to_ids(tokens)
print(token_ids)

[50, 12151, 318, 4673, 12905, 2667, 15399]


practical - 4 Standard Encoding

In [ ]:
encoded =  tokenizer.encode(text)#above to codes are legacy it will directly print form text to id
print(encoded)

[50, 12151, 318, 4673, 12905, 2667, 15399]


practical - 5 Encode Directly

In [ ]:
 ids =  tokenizer.encode(text)
print(ids)

[50, 12151, 318, 4673, 12905, 2667, 15399]


In [ ]:
print(tokenizer(text)["input_ids"])
print(tokenizer.encode(text))

Practical 6 — Decode

In [ ]:
ids = tokenizer.encode(
    "Artificial intelligence is changing software engineering."
)

decoded = tokenizer.decode(ids)

print(ids)
print(decoded)

[8001, 9542, 4430, 318, 5609, 3788, 8705, 13]
Artificial intelligence is changing software engineering.


Practical 7 — Inspect individual token ↔ ID mapping

In [ ]:
text = "Machine learning"

tokens = tokenizer.tokenize(text)
ids = tokenizer.convert_tokens_to_ids(tokens)

for token, token_id in zip(tokens, ids):
    print(f"{token!r:20} -> {token_id}")

'Machine'            -> 37573
'Ġlearning'          -> 4673


In [ ]:
#Practical 8 — Inspect vocabulary size
print("Vocabulary size:", tokenizer.vocab_size)
print(len(tokenizer))

Vocabulary size: 50257
50257


In [ ]:
text = "Hello world"

without_special = tokenizer.encode(
    text,
    add_special_tokens=False,
)

with_special = tokenizer.encode(
    text,
    add_special_tokens=True,
)

print("Without:", without_special)
print("With:", with_special)

Without: [15496, 995]
With: [15496, 995]


In [ ]:
tokenizer.pad_token = tokenizer.eos_token
texts = [
    "AI is useful.",
    "Artificial intelligence is changing software engineering rapidly.",
]

encoded = tokenizer(
    texts,
    padding=True,
    return_tensors="pt",
)

print(encoded)

print(encoded["input_ids"].shape)
print(encoded["attention_mask"].shape)

{'input_ids': tensor([[20185,   318,  4465,    13, 50256, 50256, 50256, 50256, 50256],
        [ 8001,  9542,  4430,   318,  5609,  3788,  8705,  8902,    13]]), 'attention_mask': tensor([[1, 1, 1, 1, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1]])}
torch.Size([2, 9])
torch.Size([2, 9])


In [ ]:
#Practical 13 — Inspect tensor shape
text = "I am learning Hugging Face."

encoded = tokenizer(
    text,
    return_tensors="pt",
)

print(encoded["input_ids"])
print(encoded["input_ids"].shape)

tensor([[   40,   716,  4673, 12905,  2667, 15399,    13]])
torch.Size([1, 7])


In [ ]:
#Truncation
long_text = "Artificial intelligence " * 1000

encoded = tokenizer(
    long_text,
    truncation=True,
    max_length=50,
)

print(len(encoded["input_ids"]))

50


In [ ]:
#Practical 14 — Compare truncation
text = "machine learning " * 100

full = tokenizer(
    text,
    truncation=False,
)

short = tokenizer(
    text,
    truncation=True,
    max_length=20,
)

print("Original length:", len(full["input_ids"]))
print("Truncated length:", len(short["input_ids"]))

Original length: 201
Truncated length: 20


In [ ]:
texts = [
    "Hello",
    "I am learning Hugging Face",
]

dynamic = tokenizer(
    texts,
    padding=True,
)

fixed = tokenizer(
    texts,
    padding="max_length",
    truncation=True,
    max_length=20,
)

print("Dynamic length:", len(dynamic["input_ids"][0]))
print("Fixed length:", len(fixed["input_ids"][0]))

Dynamic length: 6
Fixed length: 20


In [ ]:
#Token counting
text = """
Hugging Face provides tools for working with open source
machine learning models.
"""

ids = tokenizer.encode(text)

print("Token count:", len(ids))

Token count: 17


In [ ]:
examples = [
    "Hello",
    "Hello, how are you today?",
    "Supercalifragilisticexpialidocious",
    "AI 🤖 is amazing!",
]

for text in examples:
    ids = tokenizer.encode(text)

    print("-" * 50)
    print("Text:", text)
    print("Characters:", len(text))
    print("Tokens:", len(ids))
    print("IDs:", ids)

--------------------------------------------------
Text: Hello
Characters: 5
Tokens: 1
IDs: [15496]
--------------------------------------------------
Text: Hello, how are you today?
Characters: 25
Tokens: 7
IDs: [15496, 11, 703, 389, 345, 1909, 30]
--------------------------------------------------
Text: Supercalifragilisticexpialidocious
Characters: 34
Tokens: 11
IDs: [12442, 9948, 361, 22562, 346, 396, 501, 42372, 498, 312, 32346]
--------------------------------------------------
Text: AI 🤖 is amazing!
Characters: 16
Tokens: 7
IDs: [20185, 12520, 97, 244, 318, 4998, 0]


In [ ]:
#Practical 17 — Unknown/unusual strings
examples = [
    "Siva",
    "siva4ai",
    "qwertyuiopasdfgh",
    "తెలుగు",
    "🤖🚀🔥",
]

for text in examples:
    tokens = tokenizer.tokenize(text)

    print(text)
    print(tokens)
    print()

Siva
['S', 'iva']

siva4ai
['s', 'iva', '4', 'ai']

qwertyuiopasdfgh
['q', 'wer', 'ty', 'ui', 'op', 'as', 'df', 'gh']

తెలుగు
['à', '°', '¤', 'à', '±', 'Ĩ', 'à', '°', '²', 'à', '±', 'ģ', 'à', '°', 'Ĺ', 'à', '±', 'ģ']

🤖🚀🔥
['ðŁ', '¤', 'ĸ', 'ðŁ', 'ļ', 'Ģ', 'ðŁ', 'Ķ', '¥']



In [ ]:
print("Tokenizer class:", tokenizer.__class__.__name__)
print("Fast tokenizer:", tokenizer.is_fast)
print("Vocabulary size:", tokenizer.vocab_size)
print("Model max length:", tokenizer.model_max_length)
print("Padding side:", tokenizer.padding_side)
#Right padding
#A B C PAD PAD
#Left padding
#PAD PAD A B C

print("Truncation side:", tokenizer.truncation_side)

Tokenizer class: GPT2Tokenizer
Fast tokenizer: True
Vocabulary size: 50257
Model max length: 1024
Padding side: right
Truncation side: right


In [ ]:
#Visualize left vs right padding
texts = [
    "Hello",
    "Hello, how are you?",
]

tokenizer.pad_token = tokenizer.eos_token

tokenizer.padding_side = "right"
right = tokenizer(
    texts,
    padding=True,
)

print("RIGHT")
print(right["input_ids"])

tokenizer.padding_side = "left"
left = tokenizer(
    texts,
    padding=True,
)

print("LEFT")
print(left["input_ids"])

RIGHT
[[15496, 50256, 50256, 50256, 50256, 50256], [15496, 11, 703, 389, 345, 30]]
LEFT
[[50256, 50256, 50256, 50256, 50256, 15496], [15496, 11, 703, 389, 345, 30]]


In [ ]:
inputs = tokenizer(
    [
        "AI is useful.",
        "I am studying open-source models.",
    ],
    padding=True,
    return_tensors="pt",
)

for key, value in inputs.items():
    print(key)
    print(value)
    print("Shape:", value.shape)
    print()

input_ids
tensor([[50256, 50256, 50256, 50256, 20185,   318,  4465,    13],
        [   40,   716, 11065,  1280,    12, 10459,  4981,    13]])
Shape: torch.Size([2, 8])

attention_mask
tensor([[0, 0, 0, 0, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1]])
Shape: torch.Size([2, 8])



In [ ]:
#Chat models introduce another layer: chat templates
messages = [
    {
        "role": "system",
        "content": "You are a helpful assistant."
    },
    {
        "role": "user",
        "content": "Explain LoRA."
    }
]

In [ ]:
#inspect whether a tokenizer has a chat template
from transformers import AutoTokenizer

MODEL_ID = "Qwen/Qwen2.5-0.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

print(tokenizer.chat_template)

config.json:   0%|          | 0.00/659 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

{%- if tools %}
    {{- '<|im_start|>system\n' }}
    {%- if messages[0]['role'] == 'system' %}
        {{- messages[0]['content'] }}
    {%- else %}
        {{- 'You are Qwen, created by Alibaba Cloud. You are a helpful assistant.' }}
    {%- endif %}
    {{- "\n\n# Tools\n\nYou may call one or more functions to assist with the user query.\n\nYou are provided with function signatures within <tools></tools> XML tags:\n<tools>" }}
    {%- for tool in tools %}
        {{- "\n" }}
        {{- tool | tojson }}
    {%- endfor %}
    {{- "\n</tools>\n\nFor each function call, return a json object with function name and arguments within <tool_call></tool_call> XML tags:\n<tool_call>\n{\"name\": <function-name>, \"arguments\": <args-json-object>}\n</tool_call><|im_end|>\n" }}
{%- else %}
    {%- if messages[0]['role'] == 'system' %}
        {{- '<|im_start|>system\n' + messages[0]['content'] + '<|im_end|>\n' }}
    {%- else %}
        {{- '<|im_start|>system\nYou are Qwen, created by Alibaba C

In [ ]:
messages = [
    {
        "role": "system",
        "content": "You are a helpful AI assistant."
    },
    {
        "role": "user",
        "content": "What is quantization?"
    }
]

formatted = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True,
)

print(formatted)

<|im_start|>system
You are a helpful AI assistant.<|im_end|>
<|im_start|>user
What is quantization?<|im_end|>
<|im_start|>assistant

